### ISSUE TITLE
Add info about installing/activating for Jupyter Lab?

### ISSUE THREAD

**Issue by deeplook** [davidbrochart/ipyearth#1]
It would be helpful to have some short info in the README about how to enable ipyearth when using Jupyter Lab.

**Comment by davidbrochart** [comment]
Thanks @deeplook, I added some instructions about Jupyter Lab installation in https://github.com/davidbrochart/ipyearth/commit/83ea62e80655071a1e48c2500c7ab9e6b929cc5f.
